# -*- coding: utf-8 -*-
"""Data Transformation and Data Association.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10tq1poU3VsqBe44a1unxy2c5M6xk8SZ8
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import statistics as stats
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('bestsellers with categories.csv')

data.head()

data.info()

data.isnull().any()

data['Genre'].value_counts()

"""- No need of combining categories"""

min = data['User Rating'].min()
max = data['User Rating'].max()
print("Minimum Rating", min)
print("Maximum rating", max)

bins = [3,4,5]
data['binned_rating'] = pd.cut(data['User Rating'], bins)

data.head()

rating_labels = ['Good','Excellent']
data['binned_rating'] = pd.cut(data['User Rating'], bins, labels = rating_labels)

data.head()

labels = ['User Rating','Reviews','Price','Year']

for l in labels:
  sns.distplot(data[l])
  plt.show()
  print("Skewness -", data[l].skew())

sns.boxplot(data=data, x='Genre', y='User Rating')

plt.scatter(x=data['User Rating'], y=data['Price'])
plt.show()

