# -*- coding: utf-8 -*-
"""DSCM17L3ACP - Data Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15M0kcceU3X6OtJEHiLB1pooq95O56p_Y
"""

# Import the neccessary modules
import pandas as pd
import numpy as np
import seaborn as sb
import seaborn as sns

# Read the dataset into a dataframe
df = pd.read_csv('titanic.csv', sep='\t', engine='python')

# Drop some columns which is not relevant to the analysis (they are not numeric)
cols_to_drop = ['Name', 'Ticket', 'Cabin']
df = df.drop(cols_to_drop, axis=1)

df.info()
sb.heatmap(df.isnull())

# To replace missing values with interpolated values, for example Age
df['Age'] = df['Age'].interpolate()

# Drop all rows with missin data
df = df.dropna()

df.head()

sns.countplot(x="Survived", data = df)

#Death rate is more than 500

sns.countplot(x="Survived", hue="female",  data = df, palette="winter")

sns.countplot(x="Survived", hue="male",  data = df, palette="winter")

#Womens have survived more than males

sns.countplot(x="Survived", hue="Pclass",  data = df, palette="PuBu")

df["Age"].plot.hist()

