# -*- coding: utf-8 -*-
"""Exploratory Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mj9ieEQsdZu78LyjMUpQJPW-80BUx_J2
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import statistics as stats
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('StudentsPerformance.csv')

data.head()

data.info()

data.isnull().any()

data.describe()

sns.countplot(data['gender'], palette='winter')

sns.countplot(data['race/ethnicity'], palette='winter')

sns.countplot(data['lunch'], palette='winter')

sns.countplot(data['parental level of education'], palette='winter')
plt.xticks(rotation=45)

data.groupby('race/ethnicity').size().plot(kind='pie', autopct='%.2f')

data.groupby('parental level of education').size().plot(kind='pie', autopct='%.2f')

sns.countplot(data=data, x='gender', hue='race/ethnicity', palette='winter')

sns.countplot(data=data, x='lunch', hue='gender', palette='winter')

sns.distplot(data['math score'])
print("Skewness :", data['math score'].skew())

sns.distplot(data['reading score'])
print("Skewness :", data['reading score'].skew())

sns.distplot(data['writing score'])
print("Skewness :", data['writing score'].skew())

sns.boxplot(x=data['gender'],y=data['math score'])

sns.heatmap(data.corr())

