# -*- coding: utf-8 -*-
"""DSCM18L4ACP - Multi-class Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lyJDlVJluWfTbCX0NNTz-fm0NBnlz-Wl
"""

# Question:-Fit multi-linear model
# Gas Prod.=β1⋅Por+β2⋅Brittle+β3⋅Perm+β4⋅TOC+β0

#Importing Libraries
import pandas as pd
import numpy as np
from sklearn import linear_model

#loading the datafile from the given location
file = 'https://aegis4048.github.io/downloads/notebooks/sample_data/unconv_MV_v5.csv'
df = pd.read_csv(file)

#marking the features required and the target data
features = ['Por', 'Brittle', 'Perm', 'TOC']
target = 'Prod'

#Reshaping X and Y values
X = df[features].values.reshape(-1, len(features))
y = df[target].values

#fiting the models
ols = linear_model.LinearRegression()
model = ols.fit(X, y)

#checking the values in the array from the given data
model.coef_

#Required intercept from the data
model.intercept_

#Accuracy assesment R^2
model.score(X, y)

#making future predictions(Mking future prediction for the production of gas rate for the given data)
#Por = 12 (%)
#Brittle = 81 (%)
#VR = 2.31 (%)
#AI = 2.8 (kg/m2s*10^6)

x_pred = np.array([12, 81, 2.31, 2.8])
x_pred = x_pred.reshape(-1, len(features))

#Predicting the future predicted model
model.predict(x_pred)

#Now making prediction of 2 gases production rate
"""Por = 12 (%)
Brittle = 81 (%)
VR = 2.31 (%)
AI = 2.8 (kg/m2s*10^6)"""

"""Por = 15 (%)
Brittle = 60 (%)
VR = 2.5 (%)
AI = 1 (kg/m2s*10^6)"""

x_pred = np.array([[12, 81, 2.31, 2.8], [15, 60, 2.5, 1]])
x_pred = x_pred.reshape(-1, len(features))

#Predicting models
model.predict(x_pred)

