# -*- coding: utf-8 -*-
"""DSCM17L2ACP - Data Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQwLdVnvOmljT6XY6KZfczm2EpiRFyYe
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# % matplotlib in line

match = pd.read_csv(r"matches.csv")
match.head()

match.shape

match.isnull().sum()

sns.heatmap(match.isnull(), cmap="spring")

#Since there are 636 rows also the data of umpire 3 is not available for all the 636 rows, therefore dropping that coloumn

#Printing the original Dataset again

match.head()

#Dropping the umpire 3 coloumn

match.drop("umpire3", axis=1, inplace=True)

#Printing the Dataset after dropping the coloumn

match.head()

match.dropna(inplace=True)

sns.heatmap(match.isnull(), cbar=False)

#As you can see no null values found

#Now all the null values have been removed "CHECK"

match.isnull().sum()

#Simplifying the data more by converting the string data types to integer.

#dropping the coloumn season since in the date coloumn that year ha salready been mentioned so dropping it

match.drop("season", axis=1, inplace=True)

#Printing the Dataset after dropping the coloumn

match.head()

#Working on the deliveries dataset

balls = pd.read_csv(r"deliveries.csv")
balls.head()

balls.shape

balls.isnull().sum()

sns.heatmap(balls.isnull(), cmap="spring")

balls.dropna(inplace=True)

sns.heatmap(balls.isnull(), cbar=False)

#Now all the null values have been removed "CHECK"

balls.isnull().sum()

#printing the new dataset

balls.head()

